Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.synced_folder "../", "/srv/dev_local", type: "rsync",
    rsync__exclude: ".git/",
    rsync__auto: true
end